export class Couriervehicle{
    id: number;
    sendername: string;
   email:string;
   phnumber:string;
   senderaddress:string;
   senderdistrict:string;
   sendercity:string;
   senderstate:string;
   sendercountry:string;
   agree: boolean;
   contacttype:string;
   repname:string;
   repphnumber:string;
   repaddress:string;
   repcity:string;
   repdistrict:string;
   repstate:string;
   repcountry:string;
   courierservice:string;
   pickupdate:Date;
   status:string;
   wt:string;
   vol:string;
   price:string;
   redeemPoints:boolean;
   vehicleid:string;
   counter:number;
   locations: string[];
   currentLocation:string;
}